### ISSUE TITLE
Languages appear in random order in dropdown

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/company-website#10]
Right now we're converting from dict to array, so ordering is undefined. 

Key line of code: https://github.com/OriginProtocol/company-website/blob/master/views/web_views.py#L155
```
try:
        available_languages = dict((l,Locale(l).get_language_name(l).capitalize()) for l in constants.LANGUAGES)
```

**Comment by Zero-1729** [comment]
What is the desired output you are looking for from the current form below?
![151653443415045136](https://user-images.githubusercontent.com/23586626/35193659-cc33a5e8-fe9d-11e7-98c4-3a41d4e1648e.png)

**Comment by wanderingstan** [comment]
That's an excellent question. This [SO answer](https://ux.stackexchange.com/a/17065/45362) seems right to me. I'd say we go with sorting by unicode like Android does.

**Comment by wanderingstan** [comment]
@Zero-1729 are you still on this one? It's moving up in priority.

**Comment by Kentoseth** [comment]
I can take a look at this one if @Zero-1729 is unavailable.

**Comment by Gzing** [comment]
Working on a PR for this issue.

**Comment by wanderingstan** [comment]
Fixed by @Gzing in https://github.com/OriginProtocol/company-website/pull/21

**Comment by wanderingstan** [comment]
Ahhh, this looks so much better!
![image](https://user-images.githubusercontent.com/673455/35403814-2b038df4-01be-11e8-9b7c-359557b4795b.png)
