### ISSUE TITLE
Programatically generate partners list

### ISSUE THREAD

**Issue by Gzing** [OriginProtocol/company-website#110]
Conversation here: https://originprotocol.slack.com/archives/C7WM37W0J/p1518566619000005

- [x] Need to have a list of partners maybe stored as a dictionary in `config` folder
- [x] Add a classname on the html element using partner name, such as `logo-partner-name` so that some css tweaks can be done.
- [ ] Pass the dictionary to the frontend via a context processor

**Comment by jyotsna1820** [comment]
Taking this on :+1:

**Comment by wanderingstan** [comment]
@jyotsna1820 be sure to consult with @micahalcorn, who has been working some css magic, especially for specific cases of centering the bottom line, odd/even numbers on bottom line, etc.

**Comment by micahalcorn** [comment]
@wanderingstan actually, it's no longer necessary to manage the offsets with the advent of [`justify-content-center`](https://getbootstrap.com/docs/4.0/utilities/flex/#justify-content). No custom CSS required. 🏆
