### ISSUE TITLE
Create a "build on Origin" interest form

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#12]
We should add a "build on Origin" form to our website to generate inbound interest from developers/projects that should be building on top of the Origin platform. Form submissions should trigger an email to our biz dev guys & be logged in a database table.

The code for the presale form should be an excellent starting point. 

Copy:

Teams all over the world are building on Origin's protocols, but we're looking for more amazing people to join our mission. 
 
Whether you're an existing blockchain company or a traditional marketplace thinking about the blockchain, we'd love to hear from you! Fill out the form below and we'll get back to you shortly.

Fields:

Name (required)
Company name (required)
Email (required)
Website
Note

**Comment by Gzing** [comment]
I am interested in getting this done. Starting work on a PR now. Thanks

**Comment by wanderingstan** [comment]
Fixed in https://github.com/OriginProtocol/company-website/pull/13

Thanks @Gzing ! Closing.
