### ISSUE TITLE
http://OriginProtocol.com/telegram returns a 404

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/company-website#122]
It is very helpful in the chat and on social media to use the URL http://OriginProtocol.com/discord to send traffic to our Discord group.  

Would it also be possible to use http://OriginProtocol.com/telegram to point to https://t.me/originprotocol to send traffic to our Telegram?

I believe it currently returns a 404.  Thank you.

**Comment by micahalcorn** [comment]
Should be resolved by 67b1a982c4ab0fc54a8643b81aa3e8adba9754b6.

**Comment by davecraige** [comment]
Thanks @micahalcorn !  https://originprotocol-com-micah.herokuapp.com/telegram appears to work correctly for me.

![screen shot 2018-03-02 at 2 10 22 pm](https://user-images.githubusercontent.com/2782676/36922250-7bb8d998-1e24-11e8-8203-3878b51cf75f.png)
