### ISSUE TITLE
High-resolution partners' logos

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/company-website#124]
a99552a79c2a317f0f85f962fd75a212269e4d49 removes some 2x and 3x `png` images that are expected to be available for the index page card deck.

![index-card-deck](https://user-images.githubusercontent.com/273937/36950613-2744572a-1fbe-11e8-8975-62828f5ff9db.gif)

As a temporary fix, I will remove the relevant `srcset` attributes and recover the alternative Propy logo. But more generally, do we want to support high-resolution raster images or ask Aure to convert all of them to vectors?

**Comment by joshfraser** [comment]
Good catch @micahalcorn. My thinking was to drop support for the high resolution images since so many of the partners were missing them & the inconsistency is bad.
