### ISSUE TITLE
Track unsubscribes in a single table

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#137]
We currently pull from 3 different mailing lists when we send out our newsletter.

Unsubscribes are only supported on our official email list, but a lot of people filled out the presale form instead. We should add unsubscribed email address to a single table to unsubscribe you regardless of which mailing list you joined (and have a universal check before sending emails).

**Comment by joshfraser** [comment]
@Gzing maybe this is something you could tackle for us?

**Comment by Gzing** [comment]
Taking this on.
