### ISSUE TITLE
Origin Protocol twitter list bot keeps adding accounts over and over

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/company-website#140]
It seems like anyone who mentions @OriginProtocol on Twitter gets automatically added to this Twitter list.  The issue is that it doesn't have a limit set, so people can be added over and over again.  I have been added about 6 times or so.  It comes across to me as a bit spammy.

Notes: This is probably low priority at this time.  And if you would like me to write this issue in another location feel free to let me know.  Thank you.

![screen shot 2018-03-13 at 2 18 03 pm](https://user-images.githubusercontent.com/2782676/37367600-7bc62852-26c9-11e8-95b7-8fbf0a3191fa.png)

**Comment by joshfraser** [comment]
Closing this as it isn't related to the repo. Will investigate though.

**Comment by davecraige** [comment]
Thanks Josh!
