### ISSUE TITLE
Logging Telegram activity to the DB

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#15]
We're getting to the point where it would be very useful for us to have our Telegram activity logged in a database. We'd like to have a history of all the messages, who joined when & make it easy to chart the grow of the community over time.

Our Telegram channel is http://t.me/originprotocol

As always, add a comment here before you get started to avoid duplicating efforts.

**Comment by Kentoseth** [comment]
Sounds like a bot would be a good idea.

However, the T&Cs should be reviewed so that we can confirm we are permitted to log every message, join-date, etc.

**Comment by joshfraser** [comment]
Just wanted to bump this up in priority. Our Telegram is growing fast and that growth is a big KPI for us.

@Kentoseth should be fine. it's public conversations in a public channel.

**Comment by Kentoseth** [comment]
I have found 2 existing loggers:

https://github.com/itulo/telegram_bot_logger

https://github.com/DarthJahus/Telegram.Group_logger

If neither of them seem applicable to our use-case, I can develop a more advanced-logger instead.

**Comment by wanderingstan** [comment]
Logger created by @Kentoseth at https://github.com/OriginProtocol/origin-telegram-logger-bot

Woot!

Let's add issues to that repo from here on. Closing out this issue.
