### ISSUE TITLE
Bug - Translation drop down is broken

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/company-website#155]
Only allows for switching language between English and Deutsch.

**Comment by mek32390** [comment]
Micah, try setting .navbar-origin {position: static;} and then .navbar .nav > li {z-index: 10000;}

See if it works for you. I was able to fix this in the browser via the console but it needs proper testing.

**Comment by micahalcorn** [comment]
@mek32390 thanks for the suggestion. I believe that the `static` positioning would break small screens. My fix probably isn't the most succinct but it seems to work.
