### ISSUE TITLE
Fix layout styling for Firefox

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#16]
Looks ugly right now

**Comment by micahalcorn** [comment]
@joshfraser I see some extra/wasted vertical spacing. Is there anything else?

**Comment by wanderingstan** [comment]
@micahalcorn I think false alarm--I shared picture of how it looked for me, not realizing I'm on version 44.0. -- from 2016!

This is what it looked like:
![image](https://user-images.githubusercontent.com/673455/35308819-b12171fc-0066-11e8-8a84-c2abdd5829cd.png)

**Comment by joshfraser** [comment]
No, it's actually still broken in modern Firefox too.

Too much vertical spacing between sections.
