### ISSUE TITLE
Discord link doesn't work with https

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/company-website#166]
https://originprotocol.com/discord

doesn't work

http://originprotocol.com/discord

does.

**Comment by DanielVF** [comment]
But https://www.originprotocol.com/discord does.

**Comment by wanderingstan** [comment]
Seems redirecting to adding the `www.` no subdomain is given should be trivial. 

I used to do stuff like that on apache all the time. @joshfraser can we do this at dns level? I'm not sure how heroku handles this. 

Or is it a security issue or something to assume they meant www?

**Comment by joshfraser** [comment]
It's actually harder to do than it should be. We redirect the raw domain to www on Heroku at the DNS level but the path doesn't forward.

Let's just make sure we use the www version for now.

**Comment by wanderingstan** [comment]
Ok then. Closing.
