### ISSUE TITLE
Provide visitors with a Terms of Use Page

### ISSUE THREAD

**Issue by acal** [OriginProtocol/company-website#179]
A terms of use page and a footer nav hyperlink to it should be provided. The copy of such should be provided by legal. Legal can also determine if this is a necessary document to provide to users. IF so then a link to the page should be made clearly visible in a location like the footer nav.

**Comment by joshfraser** [comment]
Added http://www.originprotocol.com/tos & a link in the footer. Will open a new issue re: internationalization.
