### ISSUE TITLE
Add links to other languages for SEO

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/company-website#18]
We should add references to other languages available in our header, per advice here:
https://moz.com/community/q/best-practice-for-url-language-country#reply_318293

```
 ... in the <head> tag in the HTML:
<link rel=”alternate” hreflang=”en” href=”http://www.example.com/english/” />
<link rel=”alternate” hreflang=”de” href=”http://www.example.com/deutsch/"/>

```

**Comment by jyotsna1820** [comment]
Taking on this issue, will submit a PR soon.
