### ISSUE TITLE
Internationalized product brief is not linked correctly

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/company-website#185]
For languages where we have translated the product brief, the URL should point to the translated version instead of the english version.

See simplified Chinese as an example.

**Comment by joshfraser** [comment]
The internationalization seems to work for me.

Switch to simplified Chinese and the product brief links on the website change to:
https://www.originprotocol.com/zh_Hans/product-brief

Which loads the internationalized version pf the product brief. Can you give a better description of where this is broken?

**Comment by matthewliu** [comment]
Sorry, not the header link. The big blue button that says Read Our Product Brief.
