### ISSUE TITLE
Subtle whitepaper link is not internationalized

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/company-website#195]
One of the whitepaper links on the home page does not properly link to languages other than `en`. The relevant line in the template is [here](https://github.com/OriginProtocol/company-website/blob/master/templates/index.html#L421). In order to satisfy this issue, the following criteria should be met:

- [x] The entire phrase _"Product Brief and Whitepaper released"_ should be contained within a single `gettext` helper so that it gets translated effectively.
- [x] Both the phrase "Product Brief" and word "Whitepaper" should be separately linked to the relevant URL for the `CURRENT_LANGUAGE`.

@wanderingstan suggests that a possible solution might involve passing `url_for` as an argument to to `gettext`.

**Comment by wanderingstan** [comment]
Some So discussion here on best ways to do var substitution in `getext()` : https://stackoverflow.com/questions/2901082/best-practice-for-string-substition-with-gettext-using-python
