### ISSUE TITLE
Update roadmap on index page

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/company-website#211]
If you need help, please ask in our [#engineering channel on Discord](https://www.originprotocol.com/discord).

We use issues for tracking features, bugs and discussions.

Let's change it to this.
May 2017
Idea conception and demo DApp development
September 2017
Product Brief and Whitepaper released
December 2017
Launch alpha on Ethereum testnet
Q2 2018
Beta on testnet and community sale
Q3 2018
Platform launch and token distribution
2019
Launch of 3rd-party DApps and additional services

**Comment by micahalcorn** [comment]
This seems to have been completed by https://github.com/OriginProtocol/company-website/commit/0c2b48d264aa0b53ff0a08ad23a7ad291b821b38.
