### ISSUE TITLE
Translations - Arabic

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/company-website#27]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/ar/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by wanderingstan** [comment]
This was done by "m.alqattan".
