### ISSUE TITLE
Translations - Japanese

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/company-website#31]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/ja/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by wanderingstan** [comment]
Fixed in https://github.com/OriginProtocol/company-website/commit/61985973f10eb559a5e9ba3f8f44a26f132ca034
