### ISSUE TITLE
Translations - Portugese

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/company-website#34]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/pt/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by wanderingstan** [comment]
"@Emm" on Slack is on this.

**Comment by wanderingstan** [comment]
Already fixed.
