### ISSUE TITLE
Translations - Thai

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/company-website#35]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/th/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by wanderingstan** [comment]
Done.
