### ISSUE TITLE
Translations - Chinese (Simplified)

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/company-website#36]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/zh_Hans/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by wanderingstan** [comment]
Anson is now doing our Chinese translations, the Google translator toolkit. Ping me if you want to help.

**Comment by wanderingstan** [comment]
Done by Anson
