### ISSUE TITLE
Use case buttons are too far apart on specific screen sizes

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/company-website#51]
This happens when the buttons wrap on screens < `356px` and `768px`-`991px`.

<img width="1280" alt="screen shot 2018-01-29 at 5 16 04 pm" src="https://user-images.githubusercontent.com/273937/35539721-65b925fa-0518-11e8-9f89-d86b5291243f.png">

**Comment by wanderingstan** [comment]
@micahalcorn They're looking good to me now. I'm gonna call this closed. 

![image](https://user-images.githubusercontent.com/673455/36233814-0b491db6-11a5-11e8-972b-f57304514a36.png)
