### ISSUE TITLE
Add a robots.txt file

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/company-website#57]
Good for seo, and needed to user tools like http://browsershots.org/

**Comment by Zero-1729** [comment]
A **robots.txt** is definitely needed to avoid such errors.

The fix could be:
+ to add a **robots.txt** file to the `docs/` folder or possibly create a seperate `files/` folder to include it in.
[This](https://github.com/OriginProtocol/company-website/files/1684723/robots.txt) could be the **robots.txt** file.

+ Then finally add the following lines to `views/web_views.py`:
    
    ```py
    @app.route('/robots.txt')
    def robots():
        return app.send_static_file('docs/robots.txt')  # or app.send_static_file('files/robots.txt')
    ```

Let me know what you think before I make any PRs :smiley:

**Comment by wanderingstan** [comment]
@Zero-1729 Sorry to be so late on this. 

Yes, that looks great. There's nothing we need to hide from crawlers. 

You want to submit that PR?

**Comment by Zero-1729** [comment]
@wanderingstan No worries. 
Just submitted the PR :shipit:

**Comment by wanderingstan** [comment]
THanks @Zero-1729 ! Merged and pushed to production.
