### ISSUE TITLE
Adding the product brief in multiple languages

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#58]
We will soon have our product brief available in some (not all) other languages. We need a way to link to these.

Here's my initial idea. 

If your language is set to English or a language we don't support yet, the product brief link directs to the English version.

If your language is set to one of the available localized versions, we swap out the product brief link for a drop-down that offers both the local language and the English version.

The product brief link in the footer should be a drop-down that lists all available languages.

The product brief button should link to the localized version or fallback to English

**Comment by joshfraser** [comment]
The new translations are in! Let's figure out how we want to show them on the site.

We have Japanese, Korean, Russian, Simplified Chinese & Traditional Chinese

**Comment by Kentoseth** [comment]
Can you share a copy of 1 of the translations here (via attachment)?

**Comment by wanderingstan** [comment]
That's great!

I wonder if the extra drop-downs are needed? If someone wants the English version of a document, they know they can switch their language to English on the toolbar and get it. And if the document is not available in the user's chosen language, its not so unusual that the English version is substituted.

**Comment by joshfraser** [comment]
Translations can be found here:

https://www.originprotocol.com/static/docs/product_brief_v17_ja.pdf
https://www.originprotocol.com/static/docs/product_brief_v17_ko.pdf
https://www.originprotocol.com/static/docs/product_brief_v17_ru.pdf
https://www.originprotocol.com/static/docs/product_brief_v17_zh_hans.pdf
https://www.originprotocol.com/static/docs/product_brief_v17_zh_hant.pdf

@wanderingstan good point. Let's forget the dropdown in the header then.

**Comment by wanderingstan** [comment]
Have it working on live, with updated navbar and footer links.

E.g.
`https://www.originprotocol.com/ko/product-brief` forwards to 
`https://www.originprotocol.com/static/docs/product_brief_v17_ko.pdf`

@joshfraser Is there a reason we're keeping version number in filename? It makes the translating logic a little trickier, and could lead to people posting/exchanging links to outdated versions.

**Comment by joshfraser** [comment]
Fine to drop the version number from the filename. It made it easier to track while we were rapidly  iterating, but I expect edits should be slowing down at this point.

I've been meaning to fix this for a while. Let's have https://www.originprotocol.com/ko/product-brief return the actual contents of the PDF instead of the ugly redirect.

**Comment by wanderingstan** [comment]
Ugly redirect removed in e0085bfa6ef5a509cebd6ac831e5cf30a7aa9822 and pushed to live.

With that gone, its no big deal to leave version number in filename since it's no longer part of the served URL. So lets leave them in for bookkeeping.

**Comment by joshfraser** [comment]
sweet! let's fix the whitepaper URL too.

**Comment by wanderingstan** [comment]
whitepaper fixed in https://github.com/OriginProtocol/company-website/commit/8133662ccbea4ed3ce321194fb48413c0da5c4b1

Calling this closed.
