### ISSUE TITLE
Setup database migrations

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/company-website#59]
Looks like we're going to have more database stuff than we initially thought. We're going to need to set up database migrations to make it more manageable when we need to make changes to the database.

Flask-Migrate is probably the best way to go here. We just need someone to set it up. 

https://flask-migrate.readthedocs.io/en/latest/

**Comment by hucares** [comment]
lock.aquire()

**Comment by wanderingstan** [comment]
@joshfraser @hucares This is now done, right?

**Comment by hucares** [comment]
Yes. Issue should auto close on github when referenced by PR that’s closed
but doesn’t for some reason

**Comment by wanderingstan** [comment]
Sweet. Thanks for your help on that, @hucares !
