### ISSUE TITLE
Partners Page

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/company-website#79]
We need a new partners page. Aure has the design. Micah has begun to build. 

See initial conversation here: https://github.com/OriginProtocol/company-website/pull/78

**Comment by micahalcorn** [comment]
@wanderingstan I believe that https://github.com/micahalcorn/company-website/tree/issue/79_partners_page is ready for another round of comments and testing (including the form).

[Aure think's we're almost there.](https://originprotocol.slack.com/archives/C72PD95H9/p1517713198000043)

I have not revised [the copy](https://originprotocol.slack.com/archives/C7WM37W0J/p1517687644000086). Is that something I should attempt, or is that someone else's expertise?

I tried to deploy to a Heroku instance and I'm getting some errors in the log that I haven't taken time to diagnose yet. I figure that we can deal with that out after we get this page deployed to production.

**Comment by wanderingstan** [comment]
Its there and looking good!
