### ISSUE TITLE
Background changes when using search bar to reload page

### ISSUE THREAD

**Issue by evra6965** [OriginProtocol/company-website#93]
![screen shot 2018-02-09 at 4 20 51 pm](https://user-images.githubusercontent.com/33300035/36054751-4544264e-0db5-11e8-8bce-17f541e793a3.png)

Using Safari Browser. After the origin protocol website is loaded, if a user clicks in the search bar and presses enter the website reloads but with a background graphical error.

**Comment by micahalcorn** [comment]
Hi, @evra6965, thanks for reporting this issue. Are you viewing the German translation (https://www.originprotocol.com/de) both times that you load the page? Can you tell us what version of Safari you are using?

**Comment by evra6965** [comment]
Yes I am viewing the German page however It appears to be happening on all of them

Safari Version 11.0.3 (11604.5.6.1.1)

**Comment by evra6965** [comment]
Its on OS X El Capitan, Version 10.11.6 (15G19009)
So it is somewhat dated

**Comment by micahalcorn** [comment]
Got it, thanks. I'm not able to reproduce it on my machine, but we'll see if we can find a way. 🙏
