### ISSUE TITLE
Malformed HTML when tags are in translated strings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/company-website#96]
**Example**
[`<label for="note">{{gettext("<strong>Anything else we should know?</strong> (optional)")}}</label>`](https://github.com/OriginProtocol/company-website/blob/master/templates/partners.html#L267)

**Result**
<img width="1680" alt="screen shot 2018-02-10 at 12 14 59 am" src="https://user-images.githubusercontent.com/273937/36082554-39c628dc-0f70-11e8-8746-dcdb0d8dc467.png">

**To Do**
~~1) Remove tags from `gettext` strings~~
2) Manually edit existing `messages.po` files

**Comment by micahalcorn** [comment]
Here are the strings that need manual edits: https://github.com/micahalcorn/company-website/commit/3f5ee845dfae152fd791ff52c54d5a554b9360d1

**Comment by evra6965** [comment]
I am on it!

**Comment by wanderingstan** [comment]
I think we got all these fixed. Thanks @evra6965 for your help!
